name: build-pages

on:
  push:
    branches:
      - 'github-pages'
    paths:
    - '**'
    - '.github/workflows/build-pages.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # -
      #   name: Cache Docker layers
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      # -
      #   name: Login to container registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: "hub.ncsa.illinois.edu"
      #     username: "${{ secrets.NCSA_HARBOR_DES_PUBLIC_USERNAME }}"
      #     password: "${{ secrets.NCSA_HARBOR_DES_PUBLIC_TOKEN }}"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: registry.gitlab.com/des-labs/compose-deployment/desdm-public:pages
          # From https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      # -
      #   # Temp fix
      #   # https://github.com/docker/build-push-action/issues/252
      #   # https://github.com/moby/buildkit/issues/1896
      #   name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      # -
      #   name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}

      -
        uses: shrink/actions-docker-extract@v3
        id: extract
        with:
          image: registry.gitlab.com/des-labs/compose-deployment/desdm-public:pages
          path: /srv/jekyll/.
      - 
        name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ steps.extract.outputs.destination }}
          name: github-pages

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
